basket/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import home_page, basket_detail, baskets_list, basket_new, task_list, task_new, task_detail


app_name = 'basket'
urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^baskets/$', views.baskets_list, name='baskets_list'),
    url(r'^baskets/(?P<pk>\d+)/$', views.basket_detail, name='basket_detail'),
    url(r'^baskets/new/$', views.basket_new, name='basket_new'),
    url(r'^task/$', views.task_list, name='task_list'),
    url(r'^task/(?P<pk>\d+)/$', views.task_detail, name='task_detail'),
    url(r'^task/new/$', views.task_new, name='task_new'),

]

smartrm/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('basket.urls')),
]

basket/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from .task_states import TaskState
import datetime


class Basket(models.Model):
    name = models.CharField(max_length=50, default='Basket')
    rmdir = models.BooleanField()
    dry_run = models.BooleanField()
    force = models.BooleanField()

    max_size = models.IntegerField(default=10000, name='max_size')
    storage_time = models.DurationField(default=datetime.timedelta(days=14))
    basket_path = models.FilePathField(path='/home/miroslav')

    def __unicode__(self):
        return self.name

class Task(models.Model):
    name = models.CharField(max_length=50, default='Task')
    state = models.IntegerField(default=TaskState.CREATED)

    basket = models.ForeignKey(Basket)

    rmdir = models.NullBooleanField()
    dry_run = models.NullBooleanField()
    force = models.NullBooleanField()

    restore = models.BooleanField()
    regex = models.BooleanField()

    path = models.TextField()

    def __unicode__(self):
        return self.name

basket/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Basket, Task

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('name', 'basket', 'rmdir', 'force', 'dry_run', 'restore', 'regex', 'paths')


class BasketForm(forms.ModelForm):

    class Meta:
        model = Basket
        fields = ('name', 'rmdir', 'force', 'dry_run', 'max_size', 'storage_time', 'basket_path')

basket/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from myrm.basket_operations import BasketManager
from myrm.move_errors import Error
from django.shortcuts import render_to_response, render, redirect
from django.http import HttpResponseRedirect
from django .views import generic
from .models import Basket, Task
from .forms import TaskForm, BasketForm
from .task_states import TaskState
import multiprocessing


def home_page(request):
    return render('basket/home.html')


def baskets_list(request):
    baskets = {
        'baskets': Basket.object.order_by('name')
    }

    return render('basket/basket_list.html', baskets)


def basket_detail(request, pk):
    basket = Basket.objects.get(pk=int(pk))
    form = BasketForm(instance=basket)

    if request.method == "POST":
        form = BasketForm(request.POST, instance=basket)

        if form.is_valid():
            form.save()

            return redirect('/basket/')

    trash = BasketManeger(
        rmdir=basket.rmdir,
        force = basket.force,
        dry_run = basket.dry_run,
        max_size = basket.max_size,
        storage_time = basket.storage_time,
        basket_path = basket.basket_path,
    )

    context = {
        'form': form,
        'basket': trash,
        'baskets': Basket.objects.all()
    }

    return render(request, 'basket/basket_detail.html', context)


def basket_new(request):
    form = BasketForm()
    if request.method == "POST":
        form = BasketForm(request.POST)
        if form.is_valid():
            basket = form.save()
            basket.save()

            return redirect('/baskets/')

    return render(request, 'basket/basket_new.html', {'form': form})


def task_detail(request, pk):
    task = Task.object.get(pk=int(pk))
    form = TaskForm(instance=task)

    if request.method == "POST":
        form = TaskForm(request.POST, instance=task)

        if form.is_valid:
            form.save()
            return redirect('/task/')

    return render(request, 'basket/task_detail.html', {'form': form})


def task_list(request):
    tasks = {
        'tasks':Task.object.order_by('name'),
    }
    return render('basket/task_detail.html', tasks)


def task_new(request):
    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)

        if form.is_valid():
            task = form.save()
            task.save()

            return HttpResponseRedirect('/task/')

    return render(request, 'basket/task_new.html', {'form': form})


def task_result(request, pk):
    task = Task.objects.get(pk=pk)

    working_task = basket_working_tasks(task.basket)

    context = {}
    if working_task:
        context = { 'task': working_task[0]}
    else:
        task.state = TaskState.WORKING
        task.save()

        context = parallel_of_task(task)

        task.state = TaskState.COMPLETED
        task.save()

    return render(request, 'basket/task_result.html', context)


def parallel_of_task(task, num_process=None):
    mgr = multiprocessing.Manager()
    result = mgr.list()
    trash = basket_from_task(task)
    paths = task.paths.split()

    if num_process is None:
        num_process = multiprocessing.cpu_count() * 2

    action, error_object = None, None

    if task.restore:
        action = 'restore'

        splited_paths = [[] for i in xrange(num_process)]
        for i in xrange(len(paths)):
            splited_paths[i % num_process].append(paths[i])

        jobs = []
        for i in xrange(num_process):
            j = multiprocessing.Process(target=restore_worker,
                                        args=(result, trash, splited_paths[i]))
            jobs.append(j)

        for j in jobs:
            j.start()

        for j in jobs:
            j.join()
    elif task.regex:
        action = 'remove'
        result = trash.remove_regex(paths[0], search_dirs=True)
    else:
        action = 'remove'

        while paths:
            paths, leafs = cut_leafs(*paths)

            splited_paths = [[] for i in xrange(num_process)]
            for i in xrange(len(leafs)):
                splited_paths[i % num_process].append(leafs[i])

            jobs = []
            for i in xrange(num_process):
                j = multiprocessing.Process(target=remove_worker,
                                            args=(result, trash, splited_paths[i]))
                jobs.append(j)

            for j in jobs:
                j.start()

            for j in jobs:
                j.join()

    context = {
        'result': result,
        'action': action,
        'error_object': error_object,
    }

    return context


def basket_from_task(task):
    """Creates and returns BasketManager object from task.
    Task flags overlap BaskeModel flags.
    """
    basket_model = task.basket

    trash = BasketManager(
        rmdir=basket_model.rmdir,
        force=basket_model.force,
        dry_run=basket_model.dry_run,
        max_size=basket_model.max_size,
        storage_time=basket_model.storage_time,
        basket_path=basket_model.basket_path,
    )

    if task.rmdir is not None:
        trash.rmdir = task.rmdir

    if task.force is not None:
        trash.force = task.force

    if task.dry_run is not None:
        trash.dry_run = task.dry_run

    return trash


def basket_working_tasks(basket_model):
    """Checks if wastebasket_model has a working tasks.
    Returns the list of running task.
    """

    tasks = Task.objects.filter(basket__exact=basket_model)

    working_tasks = []
    for task in tasks:
        if task.state == TaskState.WORKING:
            working_tasks.append(task)

    return working_tasks


def restore_worker(result, trash, paths):
    """Function for parallel restoring files."""

    result.extend(trash.restore(*paths))


def remove_worker(result, trash, paths):
    """Function for restoring files."""
    result.extend(trash.remove(*paths))

basket/templates/basket/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>
            {% block title %}
            {% endblock %}
        </title>

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    </head>

    <body>
        <nav class="navbar navbar-toggleable-md navbar-inverse" style="background-color: #092E20;">
            {% block top_menubar %}{% endblock %}
        </nav>
        <div class="container-fluid">
            <div class="row">
                {% block content %}{% endblock %}
            </div>
        </div>

        <!-- jQuery first, then Tether, then Bootstrap JS. -->
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    </body>
</html>

basket/templates/basket/basket_detail.html
{% extends "basket/basket_list.html" %}

{% block detail %}
    <div class="container-fluid">
        <div class="row">
            <form method="POST">
                {% csrf_token %}

                <div class="col-xl-6">
                    <table class="table" >{{ form.as_table }}</table>
                    <button type="submit" class="btn btn-primary"> Save</button>
                </div>
            </form>

             <div class="col-xl-6">
                <h2>Content:</h2>
                <ul class="list-group">
                    {% for path in basket.content %}
                        <li class="list-group-item">{{ path }}</li>
                    {% endfor %}
                </ul>
             </div>
        </div>
    </div>
{% endblock %}

basket/templates/basket/basket_list.html
{% extends "basket/home.html" %}

{% block title %}Basket list{% endblock %}

{% block top_menubar %}
    {{ block.super }}
    <a class="navbar-brand navbar-toggler-right" href= {% url 'basket:basket_new' %}>Add</a>
{% endblock %}

{% block content%}
    {% if baskets %}
        <nav class="col-xl-1 bg-faded sidebar">
            <ul class="nav nav-pills filex-column">
            {% for trash in baskets %}
                <li class="nav-item">
                    <a class="nav-link" href= {% url 'basket:basket_detail' trash.pk %}>{{ trash }}</a></li>
            {% endfor %}
            </ul>
        </nav>
    {% else %}
        <div class="alert alert-warning" role="alert">
            <strong>Warning!</strong> No wastebaskets found
        </div>
    {% endif %}

     <div class="col-x-11">
         {% block detail %}
         {% endblock %}
     </div>
{% endblock %}

basket/templates/basket/basket_new.html
{% extends "basket/home.html" %}
{% block title %}New basket{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}

            <table class="table">{{ form.as_p }}</table>

            <button type="submit" class="btn btn-primary">Save</button>

        </form>
    </div>
{% endblock %}

basket/templates/basket/home.html
{% extends 'basket/base.html' %}

{% block title %}Home{% endblock %}

{% block top_menubar %}
        <a class="navbar-brand" href= {% url 'basket:basket_list' %}>Baskets</a>
        <a class="navbar-brand" href= {% url 'basket:task_list' %}>Tasks</a>
{% endblock %}

basket/templates/basket/task_detail.html
{% extends "basket/home.html" %}

{% block title %}
    {{ form.name.value }}
{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST">
         {% csrf_token %}

         <table class="table">{{ form.as_table }}</table>

         <button type="submit" class="btn btn-primary">Save</button>
         </form>
    </div>
{% endblock %}

basket/templates/basket/task_list.html
{% extends "basket/home.html" %}

{% block title %}Task list{% endblock %}

{%block top_menubar%}
    {{ block.super }}
    <a class="navbar-brand navbar-toggler-right" href= {% url 'basket:task_new' %}>Add</a>
{% endblock %}

{% block content %}
    {% if tasks %}
     <div class="table-responsive">
        <table class="table">
             <thead>
                    <th>Name</th>
                    <th>Basket</th>
                    <th>Rmdir</th>
                    <th>Force</th>
                    <th>Dry-run</th>
                    <th>Restore</th>
                    <th>Regex</th>
                    <th>Run</th>
                </thead>
             <tbody>
                 {% for task in tasks %}
                     <tr>
                         <td><a href= {% url 'basket:task_detail' task.pk %}>{{ task }}</a></td>
                         <td>{{ task.basket }}</td>
                         <td>{{ task.rmdir }}</td>
                         <td>{{ task.force }}</td>
                         <td>{{ task.dry_run }}</td>
                         <td>{{ task.restore }}</td>
                         <td>{{ task.regex }}</td>
                         <td><a href= {% url 'basket:task_result' task.pk %}>RUN</a></td>
                     </tr>
                 {% endfor %}
             </tbody>
        </table>
     </div>
   {% else %}
        <div class="alert alert-warning" role="alert">
            <strong>Warning!</strong> No tasks found
        </div>
   {% endif %}

{% endblock%}

basket/templates/basket/task_new.html
{% extends "basket/home.html" %}

{% block title %}New task{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}

            <table class="table">
                {{ form.as_table }}
            </table>
            <input type="submit" value="SAVE">
            <button type="submit" class="btn btn-primary">Save</button>

        </form>

    </div>
{% endblock %}

basket/templates/basket/task_result.html
{% extends "basket/home.html" %}

{% block title %}Result{% endblock %}

{% block content %}
    <table class="table">
        <thead>
            <th>Action</th>
            <th>Old path</th>
            <th>New path</th>
        </thead>
         <tbody>
            {% for src, dst in result %}
                <tr>
                    <td>{{ action }}</td>
                    <td>{{ src }}</td>
                    <td>{{ dst }}</td>
                </tr>
            {% endfor %}
          </tbody>
    </table>

    {% if task %}
        <div class="alert alert-danger" role="alert">
            <strong>Error!</strong> for "{{ task.basket }}" the task is alredy running: {{ task.name }}
        </div>
    {% elif error_object %}
        <div class="alert alert-danger" role="alert">
            <strong>Error!</strong> {{ error_object.msg}}" {{ error_object.raised_path}}"
        </div>
    {% endif %}
{% endblock %}